// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEXeRc-klQN2LmFGdhl4Xk_GSlW__lU3g',
    appId: '1:641936041012:web:80563b9207f1aaba6c9661',
    messagingSenderId: '641936041012',
    projectId: 'iotcw-8e94e',
    authDomain: 'iotcw-8e94e.firebaseapp.com',
    storageBucket: 'iotcw-8e94e.firebasestorage.app',
    measurementId: 'G-GPTED1M39V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArUKKMLDUfkgbsyP7QTR0vRPOMfzZ6CwA',
    appId: '1:641936041012:android:bc7ede287d1f5d616c9661',
    messagingSenderId: '641936041012',
    projectId: 'iotcw-8e94e',
    storageBucket: 'iotcw-8e94e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFxtwkOkLZJyKD8g4kSaRBC29yNYl0PcE',
    appId: '1:641936041012:ios:a1b96a1c4b08af896c9661',
    messagingSenderId: '641936041012',
    projectId: 'iotcw-8e94e',
    storageBucket: 'iotcw-8e94e.firebasestorage.app',
    iosBundleId: 'com.example.appCw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFxtwkOkLZJyKD8g4kSaRBC29yNYl0PcE',
    appId: '1:641936041012:ios:a1b96a1c4b08af896c9661',
    messagingSenderId: '641936041012',
    projectId: 'iotcw-8e94e',
    storageBucket: 'iotcw-8e94e.firebasestorage.app',
    iosBundleId: 'com.example.appCw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEXeRc-klQN2LmFGdhl4Xk_GSlW__lU3g',
    appId: '1:641936041012:web:23286495397d6a766c9661',
    messagingSenderId: '641936041012',
    projectId: 'iotcw-8e94e',
    authDomain: 'iotcw-8e94e.firebaseapp.com',
    storageBucket: 'iotcw-8e94e.firebasestorage.app',
    measurementId: 'G-76SPYNK5HP',
  );
}
